/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutContactRouteImport } from './routes/_layout/contact'
import { Route as LayoutProcessRouteImport } from './routes/_layout/process'
import { Route as LayoutReviewsRouteImport } from './routes/_layout/reviews'
import { Route as LayoutServicesRouteImport } from './routes/_layout/services'
import { Route as LayoutWhyUsRouteImport } from './routes/_layout/why-us'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutContactRoute = LayoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProcessRoute = LayoutProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReviewsRoute = LayoutReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutServicesRoute = LayoutServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutWhyUsRoute = LayoutWhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/contact': typeof LayoutContactRoute
  '/process': typeof LayoutProcessRoute
  '/reviews': typeof LayoutReviewsRoute
  '/services': typeof LayoutServicesRoute
  '/why-us': typeof LayoutWhyUsRoute
}
export interface FileRoutesByTo {
  '/contact': typeof LayoutContactRoute
  '/process': typeof LayoutProcessRoute
  '/reviews': typeof LayoutReviewsRoute
  '/services': typeof LayoutServicesRoute
  '/why-us': typeof LayoutWhyUsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/contact': typeof LayoutContactRoute
  '/_layout/process': typeof LayoutProcessRoute
  '/_layout/reviews': typeof LayoutReviewsRoute
  '/_layout/services': typeof LayoutServicesRoute
  '/_layout/why-us': typeof LayoutWhyUsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/contact' | '/process' | '/reviews' | '/services' | '/why-us'
  fileRoutesByTo: FileRoutesByTo
  to: '/contact' | '/process' | '/reviews' | '/services' | '/why-us' | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/contact'
    | '/_layout/process'
    | '/_layout/reviews'
    | '/_layout/services'
    | '/_layout/why-us'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/contact': {
      id: '/_layout/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof LayoutContactRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/process': {
      id: '/_layout/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof LayoutProcessRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reviews': {
      id: '/_layout/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof LayoutReviewsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/services': {
      id: '/_layout/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof LayoutServicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/why-us': {
      id: '/_layout/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof LayoutWhyUsRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutContactRoute: typeof LayoutContactRoute
  LayoutProcessRoute: typeof LayoutProcessRoute
  LayoutReviewsRoute: typeof LayoutReviewsRoute
  LayoutServicesRoute: typeof LayoutServicesRoute
  LayoutWhyUsRoute: typeof LayoutWhyUsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutContactRoute: LayoutContactRoute,
  LayoutProcessRoute: LayoutProcessRoute,
  LayoutReviewsRoute: LayoutReviewsRoute,
  LayoutServicesRoute: LayoutServicesRoute,
  LayoutWhyUsRoute: LayoutWhyUsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
